# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 10, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.generate_keys = QtWidgets.QPushButton(self.centralwidget)
        self.generate_keys.setGeometry(QtCore.QRect(530, 40, 101, 23))
        self.generate_keys.setObjectName("generate_keys")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 260, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 100, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 260, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.CipherText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(160, 270, 251, 111))
        self.CipherText.setObjectName("CipherText")
        self.PlainText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(160, 120, 251, 101))
        self.PlainText.setObjectName("PlainText")
        self.Information = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Information.setGeometry(QtCore.QRect(530, 120, 241, 101))
        self.Information.setObjectName("Information")
        self.Signature = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Signature.setGeometry(QtCore.QRect(530, 280, 241, 111))
        self.Signature.setObjectName("Signature")
        self.encryptBtt = QtWidgets.QPushButton(self.centralwidget)
        self.encryptBtt.setGeometry(QtCore.QRect(50, 430, 75, 23))
        self.encryptBtt.setObjectName("encryptBtt")
        self.decryptBtt = QtWidgets.QPushButton(self.centralwidget)
        self.decryptBtt.setGeometry(QtCore.QRect(170, 430, 75, 23))
        self.decryptBtt.setObjectName("decryptBtt")
        self.signatureBtt = QtWidgets.QPushButton(self.centralwidget)
        self.signatureBtt.setGeometry(QtCore.QRect(390, 430, 75, 23))
        self.signatureBtt.setObjectName("signatureBtt")
        self.verifyBtt = QtWidgets.QPushButton(self.centralwidget)
        self.verifyBtt.setGeometry(QtCore.QRect(530, 430, 75, 23))
        self.verifyBtt.setObjectName("verifyBtt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA_CIPHER"))
        self.generate_keys.setText(_translate("MainWindow", "generate_keys"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "CipherText"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.encryptBtt.setText(_translate("MainWindow", "encrypt"))
        self.decryptBtt.setText(_translate("MainWindow", "decrypt"))
        self.signatureBtt.setText(_translate("MainWindow", "signature"))
        self.verifyBtt.setText(_translate("MainWindow", "verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
